import Vue from 'vue'
import { Tab, Tabs, Checkbox, Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, SwipeItem, Grid, GridItem, Icon, Lazyload, Rate, ActionSheet, Dialog } from 'vant'

Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Rate)
Vue.use(NavBar)
Vue.use(Checkbox)
Vue.use(Toast)
Vue.use(Icon)
Vue.use(Lazyload)
Vue.use(Tabs)
Vue.use(ActionSheet)
Vue.use(Tab)
Vue.use(Dialog)
